### ISSUE TITLE
How can I run this socks server on VPS

### ISSUE THREAD

**Issue by tasi788** [concision/docker-windscribe-socks-server#6]
I've try to run on my VPS, but not works. 

===
OS: ubuntu 18.04 x64 @vultr

**Comment by concision** [comment]
Unfortunately, I am unable to resolve this issue due to technical limitations with the container's IP routing (or at least without any additional assistance). The networking configuration in the container is already finicky as-is and I am not well versed in more complex Linux routing configurations. I believe only traffic from [local IP ranges](https://en.wikipedia.org/wiki/IP_address#Private_addresses) are able to connect remotely to the container due to Windscribe's internal routing configuration.

I apologize for the inconvenience this may cause.
